# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- demo/*
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username:  # jekyll-seo-tag > Owners twitter username
author: CATMS # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name:  # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)


# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: USA/Chicago # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description:  # The post list page content
    feature_text: |

    feature_image: "/assets/images/placeholder.png"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/images/blue_waters.jpg" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/images/blue_waters.jpg" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "CATMS" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/images/CATMSlogo.png" # Site logo, also used in jekyll-seo-tag
description: "Research at the Center for Advanced Theory and Molecular Simulation aims at advancing the frontiers of theoretical chemistry through the development of new theoretical approaches and novel simulation tools, which are applied to a wide range of problems. A variety of theoretical and computational approaches are used, including electronic structure methods, classical and quantum dynamics, statistical mechanical descriptions and control theory. Current studies focus on intramolecular energy flow, photochemical processes, dynamics of quantum liquids, coherent control, spin glasses and protein folding. The research has a strong interdisciplinary character. Faculty of the theory group hold joint appointments and/or maintain frequent interactions with the Department of Physics, the Department of Materials Science and Engineering, the Center for Biophysics and Computational Biology, and the Beckman Institute for Advanced Science and Technology." # Site description and default description, also used in jekyll-seo-tag
#url: "https://catms.github.io/CATMS-pending.github.io" # Site url, also used in jekyll-seo-tag
#url: "localhost:3000/"
repo: "https://github.com/CATMS/CATMS.github.io"
email:
disqus:
avatarurl:

# 8. Site navigation
navigation_header:
  Home: /
  Posts: /blog/
  About: /About/
  Search: /search/

navigation_footer:
  University of Illinois at Urbana-Champaign CATMS: http://www.chemistry.illinois.edu/about/facilities/catms/

social_links:
  #Twitter:
  LinkedIn: https://www.linkedin.com/groups/8566715
  #Google+:
  GitHub: https://github.com/CATMS/
  #link:

sharing_links:
  #Twitter: "#1DA1F2"
  #facebook: "#3B5998"
  #Google+: "#DC4E41"
  #Pinterest: "#BD081C"
  #LinkedIn: "#0077B5"
  #tumblr: "#36465D"
  #Reddit: "#FF4500"
  #Hacker News: "#ff6600"
  #Designer News: "#2D72D9"
  #Email: ""
